### ISSUE TITLE
New text rendering is extremely slow

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4626]
Rendering the async track from OrbitTest can take >30ms. Time is spent mostly in Qt5Gui.dll hb_* functions. It might be due to locking in the low level text rendering code.

In my profile, this simple track takes 31ms of text rendering:
![image](https://user-images.githubusercontent.com/3687222/207634882-766afe4e-645d-477b-95a2-3c908385cec8.png)

**Comment by danielfenner** [comment]
I'm was aware that this the renderer is quite a bit slower (7x in some cases) than the old method but this seems excessive. 

Does this happen on every frame or only the first one? My understanding is that Qt has a cache for glyphs similar to what was implemented manually in the old code.

**Comment by danielfenner** [comment]
Is this a Windows or a Linux build? I might not have tested this under Windows iirc ...

**Comment by pierricgimmig** [comment]
This is Windows, it happens on every frame yes. It seems GetStringWidth() is called quite a lot, and that's calling into slow Qt code.

**Comment by florian-kuebler** [comment]
https://github.com/google/orbit/pull/4674 should fix this.

**Comment by pierricgimmig** [comment]
Thanks for #4674 @danielfenner , it's better, but I'm still seeing `DoUpdatePrimitives` run time for timer tracks being massively dominated by `AddTextTrailingCharsPrioritized` and Qt's `GetStringWidth` and `QFontMetrics::elidedText`. ~90% of the rendering of a simple capture is spent in text rendering. I'm using https://github.com/google/orbit/blob/main/contrib/automation_tests/testdata/OrbitTest_1-72.orbit for my test.

**Comment by danielfenner** [comment]
The change above removed the Qt methods for getting the width of the text and eliding it by some quicker heuristic (basically a per character lookup of the width). The `TimerTrack::DoUpdatePrimitives` is not dominating the `TimeGraph::DrawAllElements` anymore when rendering OrbitTest_1-72.orbit.
